---
- hosts: app
  gather_facts: no
  become: yes
  vars:
    image: geocoder
  tasks:
    - name: setup facts
      set_fact:
        timestamp: "{{ lookup('pipe', 'date -u +%Y%m%d%H%M%S') }}"
    - name: build docker image
      delegate_to: 127.0.0.1
      docker_image:
        build:
          path: ../
          pull: no
        name: '{{ image }}'
        source: build
        force_source: yes
    - name: save image to file
      delegate_to: 127.0.0.1
      docker_image:
        name: '{{ image }}'
        tag: latest
        archive_path: '{{ image }}.tar'
        source: local
    - name: compress image
      delegate_to: 127.0.0.1
      archive:
        path: '{{ image }}.tar'
        dest: '{{ image }}.tar.gz'
        remove: yes
    - name: upload image
      become: yes
      copy:
        src: '{{ image }}.tar.gz'
        dest: '/tmp/{{ timestamp }}-{{ image }}.tar.gz'
    - name: extract image
      become: yes
      shell: 'gunzip /tmp/{{ timestamp }}-{{ image }}.tar.gz'
      args:
        chdir: /tmp
    - name: load image
      become: yes
      docker_image:
        name: '{{ image }}'
        load_path: '/tmp/{{ timestamp }}-{{ image }}.tar'
        source: load
        force_source: yes
    - name: remove image file
      file:
        path: '/tmp/{{ timestamp }}-{{ image }}.tar'
        state: absent
    - name: start geocoder container
      become: yes
      docker_container:
        name: '{{ image }}'
        image: '{{ image }}'
        network_mode: host
        restart_policy: on-failure
        restart_retries: 10
        tty: yes
        env_file: '/home/{{ ansible_user }}/.env'
        state: started
